import type { CreateToastFnReturn } from "@chakra-ui/react";

/**
 * Generic error handler for client (Only for non-HTTP errors)
 *
 * @param error Error object
 * @param toast Toast function, generated by useToast hook from ChakraUI
 */
const genericErrorHandler = (error: unknown, toast: CreateToastFnReturn) => {
  if (import.meta.env.DEV) {
    console.error(error);
  }
  toast({
    title: "Error",
    description: String(error), // ||"Something went wrong. Please try again.",
    status: "error",
    duration: 5000,
    isClosable: true,
  });
};

export { genericErrorHandler };
